apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: dum-dashboard
data:
  TAPO_CAMERA_HOST: "192.168.2.44"
  go2rtc.yml: |
    app:
      modules:
        - api
        - ws
        - rtsp
        - mp4
    api:
      listen: ":1984"
      base_path: /camera-stream
      allow_paths:
        - /camera-stream/
        - /camera-stream/api/ws
        - /camera-stream/api/streams
    log:
      format: text
      level: info
    rtsp:
      listen: ""
    webrtc:
      listen: ""
    srtp:
      listen: ""
    streams:
      camera-low: rtsp://${TAPO_CAMERA_USERNAME}:${TAPO_CAMERA_PASSWORD}@${TAPO_CAMERA_HOST}:554/stream2
      camera-high: rtsp://${TAPO_CAMERA_USERNAME}:${TAPO_CAMERA_PASSWORD}@${TAPO_CAMERA_HOST}:554/stream1
