apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: dum-dashboard-camera-secrets
  namespace: dum-dashboard
spec:
  infisicalAuthRef:
    name: dum-dashboard-monies-infisical-auth
    namespace: dum-dashboard
  syncOptions:
    refreshInterval: 60s
    instantUpdates: false
  resyncInterval: 60
  manageSecret: true
  sources:
    - projectId: 1617f220-140c-4a04-a8e7-468a71e4ff50
      environmentSlug: prod
      secretPath: /camera
  targets:
    - name: dum-dashboard-camera-secrets
      namespace: dum-dashboard
      kind: Secret
      creationPolicy: Owner
