apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - config.yml
  - certificate.yml
  - ingress.yml
  - network-policy.yml
images:
  - name: ghcr.io/isolumi/dum-dashboard
    newTag: 8cd36e5cbc4d4d4052acc35e8779e53b8b50ab17
  - name: ghcr.io/isolumi/homelab-gateway
    newTag: 8cd36e5cbc4d4d4052acc35e8779e53b8b50ab17
