apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - config.yml
  - certificate.yml
  - ingress.yml
  - network-policy.yml
images:
  - name: ghcr.io/isolumi/dum-dashboard
    newTag: 263ee35e8eba79d7a88aced542a2ade8062b0f2d
  - name: ghcr.io/isolumi/homelab-gateway
    newTag: 263ee35e8eba79d7a88aced542a2ade8062b0f2d
