apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../config
  - config.yml
  - camera-config.yml
  - camera-infisical.yml
  - certificate.yml
  - ingress.yml
  - monies-infisical.yml
  - tool-api-infisical.yml
  - network-policy.yml
images:
  - name: ghcr.io/isolumi/dum-dashboard
    newTag: 39465ea481f84f03a38a3c814e18b88a8ebf0dc8
  - name: ghcr.io/isolumi/homelab-gateway
    newTag: 39465ea481f84f03a38a3c814e18b88a8ebf0dc8
