grafana:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

coreDns:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
