/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutDevColoursRouteImport } from './routes/_layout/dev-colours'
import { Route as LayoutTodosIndexRouteImport } from './routes/_layout/todos/index'
import { Route as LayoutCalendarIndexRouteImport } from './routes/_layout/calendar/index'
import { Route as CalendarOauthCallbackRouteImport } from './routes/calendar/oauth/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDevColoursRoute = LayoutDevColoursRouteImport.update({
  id: '/dev-colours',
  path: '/dev-colours',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosIndexRoute = LayoutTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarIndexRoute = LayoutCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => LayoutRoute,
} as any)
const CalendarOauthCallbackRoute = CalendarOauthCallbackRouteImport.update({
  id: '/calendar/oauth/callback',
  path: '/calendar/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/dev-colours': typeof LayoutDevColoursRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/calendar/oauth/callback': typeof CalendarOauthCallbackRoute
  '/calendar/': typeof LayoutCalendarIndexRoute
  '/todos/': typeof LayoutTodosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dev-colours': typeof LayoutDevColoursRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/calendar/oauth/callback': typeof CalendarOauthCallbackRoute
  '/calendar': typeof LayoutCalendarIndexRoute
  '/todos': typeof LayoutTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dev-colours': typeof LayoutDevColoursRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/calendar/oauth/callback': typeof CalendarOauthCallbackRoute
  '/_layout/calendar/': typeof LayoutCalendarIndexRoute
  '/_layout/todos/': typeof LayoutTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dev-colours'
    | '/auth/callback'
    | '/calendar/oauth/callback'
    | '/calendar/'
    | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dev-colours'
    | '/auth/callback'
    | '/'
    | '/calendar/oauth/callback'
    | '/calendar'
    | '/todos'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/dev-colours'
    | '/auth/callback'
    | '/_layout/'
    | '/calendar/oauth/callback'
    | '/_layout/calendar/'
    | '/_layout/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CalendarOauthCallbackRoute: typeof CalendarOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dev-colours': {
      id: '/_layout/dev-colours'
      path: '/dev-colours'
      fullPath: '/dev-colours'
      preLoaderRoute: typeof LayoutDevColoursRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos/': {
      id: '/_layout/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof LayoutTodosIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar/': {
      id: '/_layout/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof LayoutCalendarIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/calendar/oauth/callback': {
      id: '/calendar/oauth/callback'
      path: '/calendar/oauth/callback'
      fullPath: '/calendar/oauth/callback'
      preLoaderRoute: typeof CalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutDevColoursRoute: typeof LayoutDevColoursRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCalendarIndexRoute: typeof LayoutCalendarIndexRoute
  LayoutTodosIndexRoute: typeof LayoutTodosIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDevColoursRoute: LayoutDevColoursRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCalendarIndexRoute: LayoutCalendarIndexRoute,
  LayoutTodosIndexRoute: LayoutTodosIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CalendarOauthCallbackRoute: CalendarOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
