apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - dashboard-deployment.yml
  - dashboard-service.yml
  - gateway-deployment.yml
  - gateway-service.yml
  - gateway-rbac.yml
